language: node_js
node_js:
- lts/*
branches:
  only:
  - main
env:
  global:
    # CI=true -> warnings handled as errors
  - SH=bash CI=false PGPORT=5432 PORT=3000 DB_PORT=5432 DB_USER=postgres DB_HOST=localhost DB_DATABASE=ubereats DB_PWD=""
services:
  - postgresql
install: "./travis_install.sh"
before_script: "./travis_database.sh"
script: "./travis_script.sh"
after_success: "./travis_after_success.sh"
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: STNTF9rauVbjjjAbF8GZn66OO2bPPOeQawd+GzrGiVsLs961BxdwPf1CNOZeFDL+MAp2HRm2DGeG6A0YkI1j8B7M2qtoxvS2myH/5RrKyF18oz5+Cln4QOSI5cDGtxUfI9bkmkdpIEiwkvbPFA4as/0DAW4ZXVKttPPyjmzk9CUgZr0N0EV5iurHbd8DQBE7NmaKhIJYE/qkxwBmLzSaUu55WrpQRZZJYfBrDxrQtnY4D9f9zRrtPY3hi70qgOXz5cGV37xjxCUPG2yLLM/V/3mE7rovQO6jXqoc3VdofehzFmoVPip7LpwKtgJzrrKmnVJLYi2j6iPX6IIwOgg7+HdM7d5V2+LieQdnGLoAlqluDf2yjvPS2kxQVy/xmgvLEoTBHwC5SGW/g1iFKWAeU9uzTkx1PzKPzEcRB3+7CtvG/VF5dZCtYcGaKmGiBp1/JVj3jfO9n/HUGCQTU7yYM6tr8d/QTFfJQoFxOD5Q6t9AKkhvfrzqtE0CU2TuOWMPNVQp0fE1DCkE+/CTe4DhNDOMrHW6ctn449SGhMKvk+TICgNcXjgoQzNRoL4yIcjlZwOku1PRT+i9NPr6NRQFMBdP00T93l6A0RNPHTjR+Pbx3+prgg7/gPVWmPuxE7J5HoGoaGfNsttpWKamdhBz3CVppN2VSbPKRRp0VqQlcFI=
  app: ub-gei-es-ubeats-clone
  on:
    repo: UB-ES-2020/UBEats
    branch: main
notifications:
  slack:
    secure: dQsFXw3gn75M4pP6KUpYxnk3wZPZUhsu55y8Sq1tA+l2lVe9VndomwgBo/X0Rrf6+Kgzxz67BGnctUc0U0uaCgvCx8vMjSaTA24ltVACBylM/ua8TJxFENI3+SyRyOW8DphW6gEzu/rkoudm7s9AuCRQm6k87dYAJToh4OBNaMMvbboHehJ0OTOCd1AxO2aoTBJYsiwXXjpGybTKdR84z3VR6VG0NYNaSNsAUxUyV6MIYw/wGIh+cqi1dVhqBGJTN6VeDDYeZtbo5lFDorJp8sG1PDHpoXwPUGdEbRUq+37AfxqqmrHKV+h2eswveDYGhI9DoSx1iUoitTmqHH3lxCNM1y9hb2M3n8jhSLoMH9MhsN5vsLBz/bvvCGWTfZPQpLlUy0kjejWktK6kTSF+73SveU85rgd4QnnOS7lfhex6Zy/mx8OBOAcM9Kg+voFGhL8LUAWgZoipWLSeHvLNrR49hQ/L+pCFaX7AXmzwhBFXU13TSTw5ySWiwAZgtjyDVkHzvdTT7zofwX6Zta9TtTAk/clIRJ2cSIQrQyc3LuEdgBHQpbaxA6yzXqtknfhprYKpnBBqEpDCxE4HyqQ/3z3hU3WifQYYSlO++5iHqySrlnyNJtkWHyZvOsVI34DPC+p62J4NYiqZmQiGiqekxNruHjCTKu+zpsPmCMbMBlc=
